In [1]:
import pandas as pd

In [2]:
Orders = pd.read_csv('orders.csv')
Orders

     order_id customer_id product_id  quantity  order_date
0      O00001       C0333       P022         1    1/9/2022
1      O00002       C0068       P090         1   1/27/2022
2      O00003       C0483       P021         1   1/17/2022
3      O00004       C0214       P076         4    1/7/2022
4      O00005       C0411       P073         4   1/12/2022
...       ...         ...        ...       ...         ...
2579   O02580       C0237       P098         5  12/22/2024
2580   O02581       C0236       P007         1   12/5/2024
2581   O02582       C0029       P035         1  12/12/2024
2582   O02583       C0171       P077         1  12/16/2024
2583   O02584       C0421       P038         5   12/1/2024

[2584 rows x 5 columns]

In [3]:
Products = pd.read_csv('products.csv') 
Products

   product_id product_name     category   price
0        P001        Stage     Clothing  534.93
1        P002        Least  Accessories   56.56
2        P003       Number         Home  339.92
3        P004      Evening     Clothing  138.74
4        P005      Protect     Footwear   68.06
..        ...          ...          ...     ...
95       P096      Service     Footwear  872.76
96       P097         Away         Home  932.46
97       P098     Decision  Accessories  567.31
98       P099           So  Electronics  698.17
99       P100   Everything         Home  922.89

[100 rows x 4 columns]

In [4]:
Customers = pd.read_csv('customers.csv')
Customers

    customer_id       name  age  gender               city
0         C0001   Jennifer   56    Male      Morrisonmouth
1         C0002    William   46    Male  Port Charlesshire
2         C0003      Ellen   32    Male  South Thomasmouth
3         C0004      Sheri   60    Male         West Megan
4         C0005     Taylor   25    Male         Josephland
..          ...        ...  ...     ...                ...
495       C0496  Stephanie   37    Male         Santosport
496       C0497      Susan   41    Male           Annaside
497       C0498    Spencer   29  Female         Harrisside
498       C0499     Rachel   52    Male       Anthonymouth
499       C0500    Jasmine   50    Male         North Mark

[500 rows x 5 columns]

In [5]:
Orders_M = Orders.merge(Products[['product_id','product_name','category','price']], on = 'product_id', how = 'left')

In [6]:
Orders_MF = Orders_M.merge(Customers[['customer_id','gender','age']], on = 'customer_id', how = 'left')

In [7]:
Orders_MF.head()

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,gender,age
0,O00001,C0333,P022,1,1/9/2022,Tax,Home,185.33,Female,34
1,O00002,C0068,P090,1,1/27/2022,Perform,Electronics,947.55,Female,35
2,O00003,C0483,P021,1,1/17/2022,Art,Electronics,938.65,Male,36
3,O00004,C0214,P076,4,1/7/2022,Amount,Electronics,154.17,Male,36
4,O00005,C0411,P073,4,1/12/2022,Second,Electronics,131.85,Male,25

In [8]:
Orders_MF['Years'] = Orders_MF['order_date'].str.split('/').str[2].astype(int)

In [9]:
Orders_MF['Months'] = Orders_MF['order_date'].str.split('/').str[0].astype(int)

In [10]:
Orders_MF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2584 non-null   object
 1   customer_id   2584 non-null   object
 2   product_id    2584 non-null   object
 3   quantity      2584 non-null   int64
 4   order_date    2584 non-null   object
 5   product_name  2584 non-null   object
 6   category      2584 non-null   object
 7   price         2584 non-null   float64
 8   gender        2584 non-null   object
 9   age           2584 non-null   int64
 10  Years         2584 non-null   int64
 11  Months        2584 non-null   int64
dtypes: float64(1), int64(4), object(7)
memory usage: 242.4+ KB

In [11]:
grouped = Orders_MF.groupby('Years')
grouped.get_group(2022)

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,gender,age,Years,Months
0,O00001,C0333,P022,1,1/9/2022,Tax,Home,185.33,Female,34,2022,1
1,O00002,C0068,P090,1,1/27/2022,Perform,Electronics,947.55,Female,35,2022,1
2,O00003,C0483,P021,1,1/17/2022,Art,Electronics,938.65,Male,36,2022,1
3,O00004,C0214,P076,4,1/7/2022,Amount,Electronics,154.17,Male,36,2022,1
4,O00005,C0411,P073,4,1/12/2022,Second,Electronics,131.85,Male,25,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...
823,O00824,C0013,P080,1,12/10/2022,Organization,Footwear,642.94,Female,53,2022,12
824,O00825,C0030,P077,2,12/20/2022,Government,Clothing,233.11,Female,44,2022,12
825,O00826,C0487,P077,1,12/2/2022,Government,Clothing,233.11,Male,62,2022,12
826,O00827,C0363,P016,1,12/29/2022,Mind,Footwear,929.88,Male,64,2022,12
827,O00828,C0439,P078,2,12/11/2022,Where,Accessories,723.64,Female,18,2022,12

In [12]:
def Age_limits(Age):
    if 8< Age <18:
        return('Tenager_limit')
    elif 18< Age <40:
        return('Adult_limit')
    elif Age >40:
        return('Old_limit')

In [13]:
Orders_MF['Age_limit'] = Orders_MF.age.apply(Age_limits)

In [14]:
Orders_MF

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,gender,age,Years,Months,Age_limit
0,O00001,C0333,P022,1,1/9/2022,Tax,Home,185.33,Female,34,2022,1,Adult_limit
1,O00002,C0068,P090,1,1/27/2022,Perform,Electronics,947.55,Female,35,2022,1,Adult_limit
2,O00003,C0483,P021,1,1/17/2022,Art,Electronics,938.65,Male,36,2022,1,Adult_limit
3,O00004,C0214,P076,4,1/7/2022,Amount,Electronics,154.17,Male,36,2022,1,Adult_limit
4,O00005,C0411,P073,4,1/12/2022,Second,Electronics,131.85,Male,25,2022,1,Adult_limit
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2579,O02580,C0237,P098,5,12/22/2024,Decision,Accessories,567.31,Male,20,2024,12,Adult_limit
2580,O02581,C0236,P007,1,12/5/2024,Finish,Clothing,325.74,Male,46,2024,12,Old_limit
2581,O02582,C0029,P035,1,12/12/2024,First,Clothing,362.04,Female,42,2024,12,Old_limit
2582,O02583,C0171,P077,1,12/16/2024,Government,Clothing,233.11,Female,61,2024,12,Old_limit
2583,O02584,C0421,P038,5,12/1/2024,Black,Electronics,817.52,Female,64,2024,12,Old_limit

In [15]:
Mo = Orders_MF.Months.unique()
Mo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
Ye = Orders_MF.Years.unique()
Ye

array([2022, 2023, 2024])

In [17]:
def y_lest_sold(product):
    if  product == 3:
        return(product)

In [18]:
def m_lest_sold(product):
    if  product == 1:
        return(product)

In [19]:
def discount_customer(count):
    if count >5:
        return(count)

In [20]:
def m_discout_customers(count):
    if count >5:
        return(count)
    else:
        return("None")

In [21]:
for ye in Ye:
    print('*'*8,ye,'*'*8)
    g = Orders_MF.groupby('Years')
    ye_g = g.get_group(ye)
    Repeted_CI = ye_g.customer_id.value_counts()
    Top_selling_product = ye_g.product_name.value_counts()
    lest_s = ye_g.product_name.value_counts().apply(y_lest_sold).dropna()
    Discount_CI = ye_g.customer_id.value_counts().apply(discount_customer).dropna()
    Year_Revenue = (ye_g.quantity * ye_g.price).sum()
    print(f"-----Repeated_Coustomers_ID-----\n{Repeted_CI}\n-----Top_selling_product_names-----\n{Top_selling_product}\n-----Least_sold_product_names-----\n{lest_s}\n-----Discount_ID-----\n{Discount_CI}\n----------\n{ye}_Total_Revenue {Year_Revenue}")

******** 2022 ********
-----Repeated_Coustomers_ID-----
customer_id
C0028    6
C0267    6
C0080    6
C0129    6
C0471    5
        ..
C0032    1
C0496    1
C0365    1
C0069    1
C0363    1
Name: count, Length: 417, dtype: int64
-----Top_selling_product_names-----
product_name
Network    17
Program    17
Perform    15
Behind     15
So         15
           ..
News        4
Most        4
Follow      3
Seem        3
Protect     3
Name: count, Length: 95, dtype: int64
-----Least_sold_product_names-----
product_name
Follow     3.0
Seem       3.0
Protect    3.0
Name: count, dtype: float64
-----Discount_ID-----
customer_id
C0028    6.0
C0267    6.0
C0080    6.0
C0129    6.0
Name: count, dtype: float64
----------
2022_Total_Revenue 1357500.38
******** 2023 ********
-----Repeated_Coustomers_ID-----
customer_id
C0414    7
C0243    6
C0354    6
C0391    6
C0256    6
        ..
C0082    1
C0142    1
C0169    1
C0038    1
C0020    1
Name: count, Length: 428, dtype: int64
-----Top_selling_product_names-----
product_name
North       23
Table       20
Some        19
Program     17
Likely      15
            ..
Country      4
Possible     4
Strategy     4
Standard     3
First        3
Name: count, Length: 95, dtype: int64
-----Least_sold_product_names-----
product_name
Standard    3.0
First       3.0
Name: count, dtype: float64
-----Discount_ID-----
customer_id
C0414    7.0
C0243    6.0
C0354    6.0
C0391    6.0
C0256    6.0
C0068    6.0
Name: count, dtype: float64
----------
2023_Total_Revenue 1489071.01
******** 2024 ********
-----Repeated_Coustomers_ID-----
customer_id
C0220    9
C0310    6
C0475    6
C0258    5
C0461    5
        ..
C0156    1
C0159    1
C0455    1
C0185    1
C0305    1
Name: count, Length: 404, dtype: int64
-----Top_selling_product_names-----
product_name
Table      21
Behind     19
North      19
Program    16
Stage      14
           ..
Dream       4
Phone       4
The         3
On          3
Ask         2
Name: count, Length: 95, dtype: int64
-----Least_sold_product_names-----
product_name
The    3.0
On     3.0
Name: count, dtype: float64
-----Discount_ID-----
customer_id
C0220    9.0
C0310    6.0
C0475    6.0
Name: count, dtype: float64
----------
2024_Total_Revenue 1287689.2000000002

In [22]:
for ye in Ye:
    Creat_groups_year = Orders_MF.groupby('Years')
    Groups_year = Creat_groups_year.get_group(ye)
    print('*'*5,ye,'*'*5)
    for mo in Mo:
        Create_groups_months = Groups_year.groupby('Months')
        Groups_months = Create_groups_months.get_group(mo)
        print('*'*5,mo,'*'*5)
        Repeated_CI = Groups_months.customer_id.value_counts()
        Top_selling_products = Groups_months.product_name.value_counts()
        Least_sold_product = Groups_months.product_name.value_counts().apply(m_lest_sold).dropna()
        Discount_CI = Groups_months.customer_id.value_counts().apply(m_discout_customers).dropna()
        Months_Revenue = (Groups_months.quantity*Groups_months.price).sum()
        print(f"-----Repeated_ID-----\n{Repeated_CI}\n-----Top_selling_products-----\n{Top_selling_products}\n-----Least_sold_products-----\n{Least_sold_product}\n-----Discount_CI-----\n{Discount_CI}\n--------\n{mo}_Total_Revenue:{Months_Revenue}\n____________\n")

***** 2022 *****
***** 1 *****
-----Repeated_ID-----
customer_id
C0248    2
C0024    2
C0490    2
C0235    2
C0147    2
        ..
C0105    1
C0017    1
C0443    1
C0200    1
C0402    1
Name: count, Length: 90, dtype: int64
-----Top_selling_products-----
product_name
Table        4
Perform      3
Tax          3
Behind       3
Service      3
            ..
Country      1
Strategy     1
According    1
Feeling      1
Believe      1
Name: count, Length: 61, dtype: int64
-----Least_sold_products-----
product_name
On           1.0
List         1.0
Ready        1.0
Least        1.0
Be           1.0
Manage       1.0
Body         1.0
Amount       1.0
Art          1.0
Force        1.0
Network      1.0
Decision     1.0
Job          1.0
The          1.0
Finish       1.0
Coach        1.0
Likely       1.0
Some         1.0
Happen       1.0
Find         1.0
Operation    1.0
Value        1.0
Black        1.0
Maybe        1.0
Where        1.0
Work         1.0
Country      1.0
Strategy     1.0
According    1.0
Feeling      1.0
Believe      1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0248    None
C0024    None
C0490    None
C0235    None
C0147    None
         ...
C0105    None
C0017    None
C0443    None
C0200    None
C0402    None
Name: count, Length: 90, dtype: object
--------
1_Total_Revenue:174606.83000000002
____________

***** 2 *****
-----Repeated_ID-----
customer_id
C0184    2
C0013    2
C0491    2
C0276    2
C0267    1
        ..
C0066    1
C0052    1
C0036    1
C0249    1
C0316    1
Name: count, Length: 70, dtype: int64
-----Top_selling_products-----
product_name
Away             4
Able             3
Keep             3
Edge             3
Believe          2
Force            2
Black            2
Stage            2
Strategy         2
List             2
Such             2
Country          2
Really           2
Ready            2
Perform          2
Section          2
Trip             2
Drive            2
Art              2
Possible         1
Pay              1
Eat              1
Manage           1
Follow           1
Organization     1
Yes              1
Seem             1
Network          1
Ask              1
Operation        1
Mind             1
Number           1
Environmental    1
So               1
On               1
Maybe            1
West             1
Body             1
Least            1
Phone            1
Government       1
Same             1
Ahead            1
Be               1
Dream            1
Second           1
Some             1
Store            1
General          1
Job              1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Possible         1.0
Pay              1.0
Eat              1.0
Manage           1.0
Follow           1.0
Organization     1.0
Yes              1.0
Seem             1.0
Network          1.0
Ask              1.0
Operation        1.0
Mind             1.0
Number           1.0
Environmental    1.0
So               1.0
On               1.0
Maybe            1.0
West             1.0
Body             1.0
Least            1.0
Phone            1.0
Government       1.0
Same             1.0
Ahead            1.0
Be               1.0
Dream            1.0
Second           1.0
Some             1.0
Store            1.0
General          1.0
Job              1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0184    None
C0013    None
C0491    None
C0276    None
C0267    None
         ...
C0066    None
C0052    None
C0036    None
C0249    None
C0316    None
Name: count, Length: 70, dtype: object
--------
2_Total_Revenue:131429.46
____________

***** 3 *****
-----Repeated_ID-----
customer_id
C0083    3
C0113    2
C0092    2
C0021    2
C0473    2
        ..
C0383    1
C0401    1
C0052    1
C0206    1
C0315    1
Name: count, Length: 84, dtype: int64
-----Top_selling_products-----
product_name
Tax              4
Ahead            4
Program          4
Second           3
Ask              3
Environmental    3
Standard         3
Add              3
Manage           2
Network          2
Mind             2
Light            2
Amount           2
Foot             2
Country          2
News             2
Maybe            2
Perform          2
Stage            2
According        2
Operation        2
Really           2
Senior           2
Where            2
Around           2
Job              1
Force            1
Such             1
The              1
Believe          1
Pay              1
Town             1
Feeling          1
Decision         1
Eat              1
Why              1
Night            1
Most             1
Some             1
List             1
Ready            1
Body             1
Seem             1
Number           1
Be               1
Prepare          1
Follow           1
Keep             1
So               1
Dream            1
General          1
Service          1
Many             1
Possible         1
Phone            1
Consumer         1
Work             1
Detail           1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Job         1.0
Force       1.0
Such        1.0
The         1.0
Believe     1.0
Pay         1.0
Town        1.0
Feeling     1.0
Decision    1.0
Eat         1.0
Why         1.0
Night       1.0
Most        1.0
Some        1.0
List        1.0
Ready       1.0
Body        1.0
Seem        1.0
Number      1.0
Be          1.0
Prepare     1.0
Follow      1.0
Keep        1.0
So          1.0
Dream       1.0
General     1.0
Service     1.0
Many        1.0
Possible    1.0
Phone       1.0
Consumer    1.0
Work        1.0
Detail      1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0083    None
C0113    None
C0092    None
C0021    None
C0473    None
         ...
C0383    None
C0401    None
C0052    None
C0206    None
C0315    None
Name: count, Length: 84, dtype: object
--------
3_Total_Revenue:147872.94999999998
____________

***** 4 *****
-----Repeated_ID-----
customer_id
C0500    1
C0142    1
C0181    1
C0208    1
C0266    1
C0471    1
C0146    1
C0469    1
C0178    1
C0311    1
C0477    1
C0003    1
C0209    1
C0287    1
C0151    1
C0412    1
C0449    1
C0129    1
C0495    1
C0248    1
C0388    1
C0349    1
C0442    1
C0060    1
C0196    1
C0347    1
C0410    1
C0490    1
C0275    1
C0128    1
C0205    1
C0039    1
C0244    1
C0112    1
C0094    1
C0256    1
C0121    1
C0447    1
C0118    1
C0429    1
C0080    1
C0062    1
C0315    1
C0491    1
C0191    1
C0253    1
C0252    1
C0144    1
C0385    1
C0028    1
C0245    1
C0258    1
C0441    1
C0235    1
C0236    1
Name: count, dtype: int64
-----Top_selling_products-----
product_name
Many             3
Behind           3
Add              3
Everything       2
Detail           2
Program          2
Least            2
Organization     2
Amount           1
Edge             1
Why              1
Art              1
List             1
General          1
News             1
Some             1
Section          1
Prepare          1
Able             1
Environmental    1
So               1
Network          1
West             1
Evening          1
Perform          1
Value            1
Town             1
Such             1
Body             1
Store            1
Around           1
Same             1
Service          1
North            1
Senior           1
Stage            1
Keep             1
Night            1
Part             1
Market           1
Country          1
Compare          1
Trip             1
Mind             1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Amount           1.0
Edge             1.0
Why              1.0
Art              1.0
List             1.0
General          1.0
News             1.0
Some             1.0
Section          1.0
Prepare          1.0
Able             1.0
Environmental    1.0
So               1.0
Network          1.0
West             1.0
Evening          1.0
Perform          1.0
Value            1.0
Town             1.0
Such             1.0
Body             1.0
Store            1.0
Around           1.0
Same             1.0
Service          1.0
North            1.0
Senior           1.0
Stage            1.0
Keep             1.0
Night            1.0
Part             1.0
Market           1.0
Country          1.0
Compare          1.0
Trip             1.0
Mind             1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0500    None
C0142    None
C0181    None
C0208    None
C0266    None
C0471    None
C0146    None
C0469    None
C0178    None
C0311    None
C0477    None
C0003    None
C0209    None
C0287    None
C0151    None
C0412    None
C0449    None
C0129    None
C0495    None
C0248    None
C0388    None
C0349    None
C0442    None
C0060    None
C0196    None
C0347    None
C0410    None
C0490    None
C0275    None
C0128    None
C0205    None
C0039    None
C0244    None
C0112    None
C0094    None
C0256    None
C0121    None
C0447    None
C0118    None
C0429    None
C0080    None
C0062    None
C0315    None
C0491    None
C0191    None
C0253    None
C0252    None
C0144    None
C0385    None
C0028    None
C0245    None
C0258    None
C0441    None
C0235    None
C0236    None
Name: count, dtype: object
--------
4_Total_Revenue:99819.55999999998
____________

***** 5 *****
-----Repeated_ID-----
customer_id
C0324    2
C0243    1
C0216    1
C0458    1
C0274    1
C0403    1
C0129    1
C0025    1
C0354    1
C0111    1
C0430    1
C0231    1
C0134    1
C0287    1
C0177    1
C0063    1
C0075    1
C0102    1
C0333    1
C0182    1
C0090    1
C0250    1
C0456    1
C0315    1
C0328    1
C0208    1
C0083    1
C0161    1
C0364    1
C0331    1
C0455    1
C0383    1
C0495    1
C0086    1
C0065    1
C0339    1
C0108    1
C0053    1
C0480    1
C0028    1
C0269    1
C0054    1
C0080    1
C0159    1
C0378    1
C0321    1
C0270    1
C0018    1
C0441    1
Name: count, dtype: int64
-----Top_selling_products-----
product_name
Change        2
Part          2
Phone         2
Store         2
Detail        2
Find          2
Senior        2
The           2
Tax           2
Everything    2
Why           1
Likely        1
Program       1
Table         1
Least         1
Service       1
Pay           1
Add           1
Compare       1
Number        1
Standard      1
Feeling       1
Dream         1
Art           1
Able          1
Behind        1
On            1
First         1
Amount        1
Job           1
Night         1
North         1
Drive         1
Stage         1
Evening       1
Decision      1
Many          1
Ask           1
Happen        1
Really        1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Why         1.0
Likely      1.0
Program     1.0
Table       1.0
Least       1.0
Service     1.0
Pay         1.0
Add         1.0
Compare     1.0
Number      1.0
Standard    1.0
Feeling     1.0
Dream       1.0
Art         1.0
Able        1.0
Behind      1.0
On          1.0
First       1.0
Amount      1.0
Job         1.0
Night       1.0
North       1.0
Drive       1.0
Stage       1.0
Evening     1.0
Decision    1.0
Many        1.0
Ask         1.0
Happen      1.0
Really      1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0324    None
C0243    None
C0216    None
C0458    None
C0274    None
C0403    None
C0129    None
C0025    None
C0354    None
C0111    None
C0430    None
C0231    None
C0134    None
C0287    None
C0177    None
C0063    None
C0075    None
C0102    None
C0333    None
C0182    None
C0090    None
C0250    None
C0456    None
C0315    None
C0328    None
C0208    None
C0083    None
C0161    None
C0364    None
C0331    None
C0455    None
C0383    None
C0495    None
C0086    None
C0065    None
C0339    None
C0108    None
C0053    None
C0480    None
C0028    None
C0269    None
C0054    None
C0080    None
C0159    None
C0378    None
C0321    None
C0270    None
C0018    None
C0441    None
Name: count, dtype: object
--------
5_Total_Revenue:74185.19
____________

***** 6 *****
-----Repeated_ID-----
customer_id
C0047    2
C0338    2
C0098    2
C0063    2
C0497    2
        ..
C0123    1
C0393    1
C0314    1
C0210    1
C0057    1
Name: count, Length: 72, dtype: int64
-----Top_selling_products-----
product_name
Manage        3
First         3
Prepare       3
Network       3
So            3
General       2
Town          2
Senior        2
Find          2
Country       2
Management    2
Light         2
Value         2
Keep          2
Same          2
North         2
On            2
Government    2
Work          1
Least         1
Black         1
Pay           1
Eat           1
Dream         1
Operation     1
Edge          1
Program       1
Some          1
Yes           1
Happen        1
The           1
Finish        1
Tax           1
While         1
Strategy      1
Most          1
Mind          1
Art           1
Trip          1
Bed           1
Decision      1
Around        1
Table         1
Phone         1
Why           1
Second        1
Compare       1
Job           1
Many          1
West          1
Number        1
Standard      1
Market        1
Store         1
Ready         1
Drive         1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Work         1.0
Least        1.0
Black        1.0
Pay          1.0
Eat          1.0
Dream        1.0
Operation    1.0
Edge         1.0
Program      1.0
Some         1.0
Yes          1.0
Happen       1.0
The          1.0
Finish       1.0
Tax          1.0
While        1.0
Strategy     1.0
Most         1.0
Mind         1.0
Art          1.0
Trip         1.0
Bed          1.0
Decision     1.0
Around       1.0
Table        1.0
Phone        1.0
Why          1.0
Second       1.0
Compare      1.0
Job          1.0
Many         1.0
West         1.0
Number       1.0
Standard     1.0
Market       1.0
Store        1.0
Ready        1.0
Drive        1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0047    None
C0338    None
C0098    None
C0063    None
C0497    None
         ...
C0123    None
C0393    None
C0314    None
C0210    None
C0057    None
Name: count, Length: 72, dtype: object
--------
6_Total_Revenue:125984.33
____________

***** 7 *****
-----Repeated_ID-----
customer_id
C0292    2
C0393    2
C0050    1
C0428    1
C0273    1
C0099    1
C0286    1
C0484    1
C0213    1
C0184    1
C0360    1
C0453    1
C0406    1
C0206    1
C0337    1
C0308    1
C0463    1
C0167    1
C0392    1
C0423    1
C0312    1
C0280    1
C0185    1
C0492    1
C0372    1
C0306    1
C0070    1
C0154    1
C0439    1
C0396    1
C0471    1
C0285    1
C0080    1
C0236    1
C0071    1
C0456    1
C0120    1
C0048    1
C0371    1
C0089    1
C0420    1
C0329    1
C0375    1
C0041    1
C0472    1
C0179    1
C0477    1
C0383    1
C0476    1
C0028    1
C0022    1
C0290    1
C0258    1
C0079    1
C0498    1
C0295    1
Name: count, dtype: int64
-----Top_selling_products-----
product_name
Bed              3
Work             3
Drive            3
Behind           3
Add              3
Service          2
Environmental    2
Job              2
West             2
Some             2
Same             2
Edge             1
Market           1
Change           1
Operation        1
Body             1
Art              1
On               1
Why              1
Consumer         1
Eat              1
Part             1
Protect          1
Number           1
Night            1
Yes              1
Value            1
Believe          1
Around           1
Many             1
The              1
Find             1
Table            1
Everything       1
So               1
While            1
Mind             1
Pay              1
Least            1
Light            1
Perform          1
Finish           1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Edge          1.0
Market        1.0
Change        1.0
Operation     1.0
Body          1.0
Art           1.0
On            1.0
Why           1.0
Consumer      1.0
Eat           1.0
Part          1.0
Protect       1.0
Number        1.0
Night         1.0
Yes           1.0
Value         1.0
Believe       1.0
Around        1.0
Many          1.0
The           1.0
Find          1.0
Table         1.0
Everything    1.0
So            1.0
While         1.0
Mind          1.0
Pay           1.0
Least         1.0
Light         1.0
Perform       1.0
Finish        1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0292    None
C0393    None
C0050    None
C0428    None
C0273    None
C0099    None
C0286    None
C0484    None
C0213    None
C0184    None
C0360    None
C0453    None
C0406    None
C0206    None
C0337    None
C0308    None
C0463    None
C0167    None
C0392    None
C0423    None
C0312    None
C0280    None
C0185    None
C0492    None
C0372    None
C0306    None
C0070    None
C0154    None
C0439    None
C0396    None
C0471    None
C0285    None
C0080    None
C0236    None
C0071    None
C0456    None
C0120    None
C0048    None
C0371    None
C0089    None
C0420    None
C0329    None
C0375    None
C0041    None
C0472    None
C0179    None
C0477    None
C0383    None
C0476    None
C0028    None
C0022    None
C0290    None
C0258    None
C0079    None
C0498    None
C0295    None
Name: count, dtype: object
--------
7_Total_Revenue:96078.60999999999
____________

***** 8 *****
-----Repeated_ID-----
customer_id
C0466    3
C0157    2
C0336    2
C0474    1
C0351    1
C0388    1
C0125    1
C0058    1
C0445    1
C0176    1
C0012    1
C0421    1
C0379    1
C0105    1
C0248    1
C0385    1
C0193    1
C0023    1
C0031    1
C0356    1
C0405    1
C0139    1
C0199    1
C0340    1
C0443    1
C0150    1
C0119    1
C0075    1
C0364    1
C0249    1
C0257    1
C0046    1
C0021    1
C0202    1
C0010    1
C0475    1
C0121    1
C0416    1
C0450    1
C0484    1
C0116    1
C0460    1
C0045    1
C0182    1
C0267    1
C0447    1
C0214    1
C0079    1
C0230    1
C0106    1
C0298    1
C0442    1
C0353    1
C0163    1
C0273    1
C0095    1
C0373    1
C0451    1
C0156    1
C0078    1
Name: count, dtype: int64
-----Top_selling_products-----
product_name
On               3
Country          3
North            2
Perform          2
Really           2
Store            2
Organization     2
Force            2
Maybe            2
Change           2
Pay              2
Prepare          1
Job              1
Value            1
Many             1
Some             1
Ask              1
Consumer         1
Program          1
Least            1
Finish           1
The              1
Town             1
Government       1
Night            1
Network          1
Yes              1
Coach            1
Most             1
Service          1
Compare          1
Environmental    1
Table            1
Operation        1
Drive            1
Phone            1
Light            1
Body             1
Part             1
Eat              1
According        1
Where            1
Foot             1
So               1
Second           1
Manage           1
Why              1
Behind           1
Evening          1
Be               1
Everything       1
Name: count, dtype: int64
-----Least_sold_products-----
product_name
Prepare          1.0
Job              1.0
Value            1.0
Many             1.0
Some             1.0
Ask              1.0
Consumer         1.0
Program          1.0
Least            1.0
Finish           1.0
The              1.0
Town             1.0
Government       1.0
Night            1.0
Network          1.0
Yes              1.0
Coach            1.0
Most             1.0
Service          1.0
Compare          1.0
Environmental    1.0
Table            1.0
Operation        1.0
Drive            1.0
Phone            1.0
Light            1.0
Body             1.0
Part             1.0
Eat              1.0
According        1.0
Where            1.0
Foot             1.0
So               1.0
Second           1.0
Manage           1.0
Why              1.0
Behind           1.0
Evening          1.0
Be               1.0
Everything       1.0
Name: count, dtype: float64
-----Discount_CI-----
customer_id
C0466    None
C0157    None
C0336    None
C0474    None
C0351    None
C0388    None
C0125    None
C0058    None
C0445    None
C0176    None
C0012    None
C0421    None
C0379    None
C0105    None
C0248    None

In [25]:
for ye in Ye:
    print('*'*6,ye,'*'*6)
    group = Orders_MF.groupby('Years')
    year_group = group.get_group(ye)
    print('_'*14)
    print(f" Total_revenue: {(year_group.quantity*year_group.price).sum()}")
    print('_'*14)
    print(f"Highly purchase {year_group['gender'].value_counts()} ")
    print('_'*14)
    print(year_group['category'].value_counts())
    print('_'*14)
    print(year_group['product_name'].value_counts())
    print('_'*14)
    print(year_group['Age_limit'].value_counts())
    print('_-_'*14)

****** 2022 ******
______________
 Total_revenue: 1357500.38
______________
Highly purchase gender
Male      466
Female    362
Name: count, dtype: int64
______________
category
Electronics    195
Accessories    173
Footwear       158
Home           153
Clothing       149
Name: count, dtype: int64
______________
product_name
Network    17
Program    17
Perform    15
Behind     15
So         15
           ..
News        4
Most        4
Follow      3
Seem        3
Protect     3
Name: count, Length: 95, dtype: int64
______________
Age_limit
Old_limit      475
Adult_limit    306
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 2023 ******
______________
 Total_revenue: 1489071.01
______________
Highly purchase gender
Male      508
Female    416
Name: count, dtype: int64
______________
category
Electronics    215
Accessories    195
Clothing       188
Footwear       170
Home           156
Name: count, dtype: int64
______________
product_name
North       23
Table       20
Some        19
Program     17
Likely      15
            ..
Country      4
Possible     4
Strategy     4
Standard     3
First        3
Name: count, Length: 95, dtype: int64
______________
Age_limit
Old_limit      487
Adult_limit    396
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 2024 ******
______________
 Total_revenue: 1287689.2000000002
______________
Highly purchase gender
Male      451
Female    381
Name: count, dtype: int64
______________
category
Electronics    180
Accessories    171
Footwear       169
Clothing       165
Home           147
Name: count, dtype: int64
______________
product_name
Table      21
Behind     19
North      19
Program    16
Stage      14
           ..
Dream       4
Phone       4
The         3
On          3
Ask         2
Name: count, Length: 95, dtype: int64
______________
Age_limit
Old_limit      471
Adult_limit    322
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_

In [24]:
for ye in Ye:
    print('*'*6,ye,'*'*6)
    group = Orders_MF.groupby('Years')
    year_group = group.get_group(ye)
    for mo in Mo:
        print('*'*6,mo,'*'*6)
        m_group = year_group.groupby('Months')
        month_group = m_group.get_group(mo)
        print('_'*14)
        print(f" Total_revenue: {(month_group.quantity*month_group.price).sum()}")
        print('_'*14)
        print(f"Highly purchase purchase {month_group['gender'].value_counts()} ")
        print('_'*14)
        print(month_group['category'].value_counts())
        print('_'*14)
        print(month_group['product_name'].value_counts())
        print('_'*14)
        print(month_group['Age_limit'].value_counts())
        print('_-_'*14)

****** 2022 ******
****** 1 ******
______________
 Total_revenue: 174606.83000000002
______________
Highly purchase purchase gender
Male      55
Female    44
Name: count, dtype: int64
______________
category
Footwear       25
Home           21
Electronics    20
Accessories    18
Clothing       15
Name: count, dtype: int64
______________
product_name
Table        4
Perform      3
Tax          3
Behind       3
Service      3
            ..
Country      1
Strategy     1
According    1
Feeling      1
Believe      1
Name: count, Length: 61, dtype: int64
______________
Age_limit
Old_limit      57
Adult_limit    40
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 2 ******
______________
 Total_revenue: 131429.46
______________
Highly purchase purchase gender
Male      45
Female    29
Name: count, dtype: int64
______________
category
Electronics    22
Home           19
Accessories    12
Clothing       11
Footwear       10
Name: count, dtype: int64
______________
product_name
Away             4
Able             3
Keep             3
Edge             3
Believe          2
Force            2
Black            2
Stage            2
Strategy         2
List             2
Such             2
Country          2
Really           2
Ready            2
Perform          2
Section          2
Trip             2
Drive            2
Art              2
Possible         1
Pay              1
Eat              1
Manage           1
Follow           1
Organization     1
Yes              1
Seem             1
Network          1
Ask              1
Operation        1
Mind             1
Number           1
Environmental    1
So               1
On               1
Maybe            1
West             1
Body             1
Least            1
Phone            1
Government       1
Same             1
Ahead            1
Be               1
Dream            1
Second           1
Some             1
Store            1
General          1
Job              1
Name: count, dtype: int64
______________
Age_limit
Old_limit      37
Adult_limit    34
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 3 ******
______________
 Total_revenue: 147872.94999999998
______________
Highly purchase purchase gender
Male      56
Female    38
Name: count, dtype: int64
______________
category
Electronics    25
Clothing       22
Accessories    18
Footwear       16
Home           13
Name: count, dtype: int64
______________
product_name
Tax              4
Ahead            4
Program          4
Second           3
Ask              3
Environmental    3
Standard         3
Add              3
Manage           2
Network          2
Mind             2
Light            2
Amount           2
Foot             2
Country          2
News             2
Maybe            2
Perform          2
Stage            2
According        2
Operation        2
Really           2
Senior           2
Where            2
Around           2
Job              1
Force            1
Such             1
The              1
Believe          1
Pay              1
Town             1
Feeling          1
Decision         1
Eat              1
Why              1
Night            1
Most             1
Some             1
List             1
Ready            1
Body             1
Seem             1
Number           1
Be               1
Prepare          1
Follow           1
Keep             1
So               1
Dream            1
General          1
Service          1
Many             1
Possible         1
Phone            1
Consumer         1
Work             1
Detail           1
Name: count, dtype: int64
______________
Age_limit
Old_limit      57
Adult_limit    33
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 4 ******
______________
 Total_revenue: 99819.55999999998
______________
Highly purchase purchase gender
Female    29
Male      26
Name: count, dtype: int64
______________
category
Electronics    17
Footwear       13
Home            9
Accessories     9
Clothing        7
Name: count, dtype: int64
______________
product_name
Many             3
Behind           3
Add              3
Everything       2
Detail           2
Program          2
Least            2
Organization     2
Amount           1
Edge             1
Why              1
Art              1
List             1
General          1
News             1
Some             1
Section          1
Prepare          1
Able             1
Environmental    1
So               1
Network          1
West             1
Evening          1
Perform          1
Value            1
Town             1
Such             1
Body             1
Store            1
Around           1
Same             1
Service          1
North            1
Senior           1
Stage            1
Keep             1
Night            1
Part             1
Market           1
Country          1
Compare          1
Trip             1
Mind             1
Name: count, dtype: int64
______________
Age_limit
Old_limit      33
Adult_limit    16
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 5 ******
______________
 Total_revenue: 74185.19
______________
Highly purchase purchase gender
Male      29
Female    21
Name: count, dtype: int64
______________
category
Home           13
Footwear       12
Accessories    10
Electronics     9
Clothing        6
Name: count, dtype: int64
______________
product_name
Change        2
Part          2
Phone         2
Store         2
Detail        2
Find          2
Senior        2
The           2
Tax           2
Everything    2
Why           1
Likely        1
Program       1
Table         1
Least         1
Service       1
Pay           1
Add           1
Compare       1
Number        1
Standard      1
Feeling       1
Dream         1
Art           1
Able          1
Behind        1
On            1
First         1
Amount        1
Job           1
Night         1
North         1
Drive         1
Stage         1
Evening       1
Decision      1
Many          1
Ask           1
Happen        1
Really        1
Name: count, dtype: int64
______________
Age_limit
Old_limit      32
Adult_limit    17
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 6 ******
______________
 Total_revenue: 125984.33
______________
Highly purchase purchase gender
Male      40
Female    39
Name: count, dtype: int64
______________
category
Accessories    23
Electronics    21
Home           15
Clothing       12
Footwear        8
Name: count, dtype: int64
______________
product_name
Manage        3
First         3
Prepare       3
Network       3
So            3
General       2
Town          2
Senior        2
Find          2
Country       2
Management    2
Light         2
Value         2
Keep          2
Same          2
North         2
On            2
Government    2
Work          1
Least         1
Black         1
Pay           1
Eat           1
Dream         1
Operation     1
Edge          1
Program       1
Some          1
Yes           1
Happen        1
The           1
Finish        1
Tax           1
While         1
Strategy      1
Most          1
Mind          1
Art           1
Trip          1
Bed           1
Decision      1
Around        1
Table         1
Phone         1
Why           1
Second        1
Compare       1
Job           1
Many          1
West          1
Number        1
Standard      1
Market        1
Store         1
Ready         1
Drive         1
Name: count, dtype: int64
______________
Age_limit
Old_limit      51
Adult_limit    24
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 7 ******
______________
 Total_revenue: 96078.60999999999
______________
Highly purchase purchase gender
Male      32
Female    26
Name: count, dtype: int64
______________
category
Electronics    17
Footwear       15
Accessories    11
Home            8
Clothing        7
Name: count, dtype: int64
______________
product_name
Bed              3
Work             3
Drive            3
Behind           3
Add              3
Service          2
Environmental    2
Job              2
West             2
Some             2
Same             2
Edge             1
Market           1
Change           1
Operation        1
Body             1
Art              1
On               1
Why              1
Consumer         1
Eat              1
Part             1
Protect          1
Number           1
Night            1
Yes              1
Value            1
Believe          1
Around           1
Many             1
The              1
Find             1
Table            1
Everything       1
So               1
While            1
Mind             1
Pay              1
Least            1
Light            1
Perform          1
Finish           1
Name: count, dtype: int64
______________
Age_limit
Old_limit      29
Adult_limit    23
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 8 ******
______________
 Total_revenue: 102602.68
______________
Highly purchase purchase gender
Male      36
Female    28
Name: count, dtype: int64
______________
category
Accessories    16
Footwear       13
Electronics    13
Clothing       12
Home           10
Name: count, dtype: int64
______________
product_name
On               3
Country          3
North            2
Perform          2
Really           2
Store            2
Organization     2
Force            2
Maybe            2
Change           2
Pay              2
Prepare          1
Job              1
Value            1
Many             1
Some             1
Ask              1
Consumer         1
Program          1
Least            1
Finish           1
The              1
Town             1
Government       1
Night            1
Network          1
Yes              1
Coach            1
Most             1
Service          1
Compare          1
Environmental    1
Table            1
Operation        1
Drive            1
Phone            1
Light            1
Body             1
Part             1
Eat              1
According        1
Where            1
Foot             1
So               1
Second           1
Manage           1
Why              1
Behind           1
Evening          1
Be               1
Everything       1
Name: count, dtype: int64
______________
Age_limit
Old_limit      37
Adult_limit    23
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 9 ******
______________
 Total_revenue: 95015.45999999999
______________
Highly purchase purchase gender
Male      34
Female    22
Name: count, dtype: int64
______________
category
Clothing       13
Electronics    13
Home           11
Accessories    10
Footwear        9
Name: count, dtype: int64
______________
product_name
Network         4
Possible        2
Prepare         2
Foot            2
Keep            2
Organization    2
Coach           2
Likely          2
Feeling         2
Tax             2
Table           1
Program         1
Black           1
Yes             1
Service         1
Behind          1
List            1
Why             1
Dream           1
Bed             1
Part            1
Job             1
Find            1
North           1
Strategy        1
Night           1
Perform         1
Ready           1
Art             1
Such            1
Standard        1
Really          1
Some            1
So              1
Change          1
Town            1
Happen          1
Stage           1
Amount          1
Be              1
Government      1
Most            1
Ahead           1
Compare         1
Name: count, dtype: int64
______________
Age_limit
Old_limit      27
Adult_limit    24
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 10 ******
______________
 Total_revenue: 78645.33
______________
Highly purchase purchase gender
Male      31
Female    28
Name: count, dtype: int64
______________
category
Clothing       20
Accessories    13
Electronics    10
Footwear        8
Home            8
Name: count, dtype: int64
______________
product_name
Program          3
Change           3
Be               3
Ahead            2
Around           2
West             2
North            2
Foot             2
Bed              2
Why              2
Prepare          2
Stage            2
Environmental    2
Evening          2
So               2
Possible         2
Market           1
Where            1
Yes              1
Manage           1
Compare          1
Management       1
Second           1
Night            1
Force            1
Part             1
Trip             1
Store            1
Body             1
Add              1
Light            1
Maybe            1
Tax              1
Operation        1
Behind           1
Strategy         1
Eat              1
Consumer         1
General          1
Everything       1
Name: count, dtype: int64
______________
Age_limit
Old_limit      37
Adult_limit    18
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 11 ******
______________
 Total_revenue: 133063.62
______________
Highly purchase purchase gender
Male      49
Female    30
Name: count, dtype: int64
______________
category
Accessories    21
Footwear       15
Electronics    15
Home           15
Clothing       13
Name: count, dtype: int64
______________
product_name
While         4
Network       3
Phone         3
Ready         3
Perform       2
Happen        2
Around        2
North         2
Dream         2
Edge          2
Table         2
Town          2
List          2
Detail        2
Eat           2
Same          2
Yes           2
Coach         2
Operation     2
According     2
Maybe         2
Some          2
Management    1
So            1
Add           1
Find          1
Standard      1
Ask           1
Away          1
Amount        1
Foot          1
Strategy      1
Evening       1
Value         1
Program       1
Bed           1
On            1
Government    1
Feeling       1
Work          1
Behind        1
Body          1
Such          1
Prepare       1
Consumer      1
Finish        1
Change        1
Store         1
Really        1
Follow        1
Least         1
Number        1
Name: count, dtype: int64
______________
Age_limit
Old_limit      42
Adult_limit    33
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 12 ******
______________
 Total_revenue: 98196.36
______________
Highly purchase purchase gender
Male      33
Female    28
Name: count, dtype: int64
______________
category
Footwear       14
Electronics    13
Accessories    12
Home           11
Clothing       11
Name: count, dtype: int64
______________
product_name
Really          2
Protect         2
Bed             2
Strategy        2
Job             2
While           2
Government      2
Body            2
General         2
Be              2
Everything      1
Program         1
Tax             1
Store           1
Network         1
Stage           1
Table           1
Force           1
Black           1
Amount          1
The             1
News            1
Dream           1
Happen          1
Feeling         1
Night           1
Seem            1
Add             1
Ready           1
Away            1
Management      1
Town            1
Light           1
West            1
Perform         1
Keep            1
Behind          1
Many            1
Prepare         1
Drive           1
First           1
So              1
Pay             1
Some            1
Same            1
Yes             1
Least           1
Believe         1
Organization    1
Mind            1
Where           1
Name: count, dtype: int64
______________
Age_limit
Old_limit      36
Adult_limit    21
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 2023 ******
****** 1 ******
______________
 Total_revenue: 108926.39
______________
Highly purchase purchase gender
Male      41
Female    33
Name: count, dtype: int64
______________
category
Accessories    19
Footwear       18
Electronics    15
Home           14
Clothing        8
Name: count, dtype: int64
______________
product_name
General         3
Mind            3
Seem            3
Protect         2
Value           2
Prepare         2
Number          2
West            2
Operation       2
Perform         2
Section         2
Some            2
Table           2
Amount          2
North           2
Such            1
Change          1
Bed             1
While           1
Light           1
The             1
Likely          1
Part            1
Believe         1
Country         1
Senior          1
Keep            1
Network         1
Second          1
Around          1
Why             1
Body            1
Feeling         1
Able            1
Program         1
Organization    1
Dream           1
Yes             1
Government      1
Pay             1
Manage          1
Detail          1
Work            1
Maybe           1
Tax             1
Drive           1
Everything      1
Away            1
Stage           1
Store           1
So              1
Happen          1
Job             1
Coach           1
Follow          1
Eat             1
Name: count, dtype: int64
______________
Age_limit
Old_limit      47
Adult_limit    25
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 2 ******
______________
 Total_revenue: 100614.26999999999
______________
Highly purchase purchase gender
Male      35
Female    22
Name: count, dtype: int64
______________
category
Home           13
Clothing       12
Footwear       12
Electronics    12
Accessories     8
Name: count, dtype: int64
______________
product_name
North         4
Program       2
While         2
Dream         2
Add           2
Tax           2
Value         2
Management    2
Force         2
Network       2
Work          2
Black         2
West          2
Some          1
Find          1
Service       1
Ask           1
Everything    1
Believe       1
News          1
Operation     1
Around        1
Be            1
Same          1
Most          1
Amount        1
Keep          1
According     1
Likely        1
Phone         1
Section       1
Edge          1
Foot          1
Maybe         1
Consumer      1
Change        1
Protect       1
Away          1
Ahead         1
Body          1
Finish        1
Standard      1
Name: count, dtype: int64
______________
Age_limit
Old_limit      33
Adult_limit    23
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 3 ******
______________
 Total_revenue: 132403.32
______________
Highly purchase purchase gender
Male      46
Female    43
Name: count, dtype: int64
______________
category
Electronics    24
Accessories    21
Clothing       18
Home           14
Footwear       12
Name: count, dtype: int64
______________
product_name
Follow           4
Foot             4
Bed              3
Art              3
Feeling          3
Table            3
Stage            3
Amount           2
On               2
Behind           2
Night            2
Store            2
Some             2
Seem             2
Value            2
Town             2
Mind             2
Such             2
Manage           2
Where            2
Likely           2
Same             2
Many             2
Consumer         2
Eat              1
Tax              1
Detail           1
Finish           1
Ready            1
General          1
Ask              1
Force            1
Change           1
Ahead            1
Happen           1
Keep             1
Strategy         1
Network          1
Black            1
Environmental    1
Number           1
So               1
Market           1
Section          1
Evening          1
Believe          1
Operation        1
Job              1
Phone            1
North            1
Maybe            1
Be               1
Management       1
Pay              1
Standard         1
Second           1
Name: count, dtype: int64
______________
Age_limit
Old_limit      54
Adult_limit    30
Name: count, dtype: int64
_-__-__-__-__-__-__-__-__-__-__-__-__-__-_
****** 4 ******
______________
 Total_revenue: 81954.66000000002
______________
Highly purchase purchase gender
Male      29
Female    22
Name: count, dtype: int64
______________
category
Accessories    13
Electronics    11
Home           10
Footwear       10
Clothing        7